from main import db
from models import db as dbmodel, Jugador,Videos
from datetime import datetime

# dbmodel.create_all()

# j = Jugador(id=0, nombre="SinDefinir", numero_camiseta="0", date=datetime.utcnow())  
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="ALEJANDRO DAVIDOVICH", numero_camiseta="14", date=datetime.utcnow())  
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="ADALBERTO VERA", numero_camiseta="24", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="ALBERT MUNOZ", numero_camiseta="0", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="ALCIDES FERNANDEZ", numero_camiseta="22", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="ANDRES TORRES", numero_camiseta="0", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="ANGEL VERA", numero_camiseta="16", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="ARTURO DELVALLE", numero_camiseta="0", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="CARLOS DOMINGUEZ", numero_camiseta="6", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="CARLOS MENDEZ", numero_camiseta="10", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="CHRISTIAN MORALES", numero_camiseta="7", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="CLAUDIO FILARTIGA", numero_camiseta="11", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="DIEGO BENITEZ", numero_camiseta="11", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="HERNAN CANTERO", numero_camiseta="0", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="JAVIER RUIZDIAZ", numero_camiseta="0", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="JORGE AMARILLA", numero_camiseta="0", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="JORGE DOMINGUEZ", numero_camiseta="0", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="JORGE RUIZ DIAZ", numero_camiseta="29", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="JOSELO RAIMUNDO", numero_camiseta="15", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="MANUEL CACERES", numero_camiseta="0", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="MANUEL FILARTIGA", numero_camiseta="9", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="MARCOS A.", numero_camiseta="80", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="PABLO CHIRIFE", numero_camiseta="3", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="OSCAR RUFFINELLI", numero_camiseta="5", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()
# j = Jugador(nombre="WILLIAN ESCOBAR", numero_camiseta="0", date=datetime.utcnow())
# dbmodel.session.add(j)
# dbmodel.session.commit()

for j in Jugador.query.all():
    print(j)

for v in Videos.query.all():
    print(v)
